server:
  port: 8081
  servlet:
    context-path: /temp
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
tmp:
  path: /opt/tmp
#logging:
#    level:
#        test: debug